# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=30, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mytrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('permission', models.ManyToManyField(to='app.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stratedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pricipal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('subscription', models.IntegerField(default=0)),
                ('purchase', models.IntegerField(default=0)),
                ('maxwithdraw', models.DecimalField(decimal_places=3, max_digits=10)),
                ('totalreturn', models.DecimalField(decimal_places=3, max_digits=10)),
                ('todayreturn', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StratedyClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('direction', models.IntegerField()),
                ('created', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dealtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DealType')),
                ('id_Stratedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stratedy')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=30)),
                ('mobile', models.CharField(default=None, max_length=30)),
                ('wechat', models.CharField(default=None, max_length=30)),
                ('alipay', models.CharField(default=None, max_length=30)),
                ('rank', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=0)),
                ('invitecode', models.CharField(default=None, max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Role')),
            ],
        ),
        migrations.AddField(
            model_name='stratedy',
            name='stratedyclassification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StratedyClassification'),
        ),
        migrations.AddField(
            model_name='stratedy',
            name='users',
            field=models.ManyToManyField(through='app.BuyRecord', to='app.User'),
        ),
        migrations.AddField(
            model_name='mytrade',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='buyrecord',
            name='stratedy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stratedy'),
        ),
        migrations.AddField(
            model_name='buyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
