# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171122_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytrade',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='mytrade',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mytrade',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mytrade',
            name='dealtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.DealType'),
        ),
        migrations.AddField(
            model_name='mytrade',
            name='direction',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mytrade',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mytrade',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
