# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171125_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='officialaccount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unionid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyrecord',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mytrade',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stratedy',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stratedy',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
