# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171126_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stratedy',
            old_name='pricipal',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='id_Stratedy',
            new_name='stratedy',
        ),
    ]
